### ISSUE TITLE
cortex-m to version 0.7.2

### ISSUE THREAD

**Issue by lightyear15** [dfrankland/mk20d7#1]
Hi,
I was wondering if you could update version for dependency ``cortex-m``
we are at version 0.7.2
If I am not mistaken the new version of ``cortex-m`` it does not depend on packages like ``untagged-option`` or ``aligned`` which require nightly.
So, if I am not mistaken`` using 0.7.2 allows to use stable rust
thanks

**Comment by Meptl** [comment]
Filed https://github.com/dfrankland/mk20d7/pull/2
